src/ioinit.o.d:  \
 /home/masterzdran/Applications/eCos/3.0/ecos-3.0/packages/io/common/v3_0/src/ioinit.cxx \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/io/io.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/system.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/hal.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/hal_arm.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/hal_arm_lpc2xxx.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/hal_arm_lpc2xxx_p2106.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/infra/cyg_type.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/stddef.h \
  /home/masterzdran/Applications/ISEL/gnutools/arm-eabi/bin/../lib/gcc/arm-eabi/4.3.2/include/stddef.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/basetype.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/error/codes.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/error.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/io/devtab.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/drv_api.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/kernel.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/infra.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/kernel/kapi.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/memalloc/kapi.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/pkgconf/memalloc.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/kernel/kapidata.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/hal_intr.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/hal_var_ints.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/lpc2xxx_misc.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/memalloc/kapidata.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/hal_tables.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/hal_arch.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/var_arch.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/hal_io.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/var_io.h \
  /home/masterzdran/WorkingArea/Isel/semestre6/SE2/workplace/eCos/3.0/eCos.ISEL.SE2.31401.build_install/include/cyg/hal/plf_io.h
