#ifndef __ETHERNET_H_
#define __ETHERNET_H_

#define MAX_FRAME_LEN   1518
#define MAX_TX_RETRY    10

#define __ETHERNET_RX_START_PTR__        0x0000
#define __ETHERNET_RX_END_PTR__          0x0FFF
#define __ETHERNET_TX_START_PTR__        0x1000
#define __ETHERNET_TX_END_PTR__          0x1F00 


#define __ETHERNET_RX_BUFFER_SIZE__   4096
#define __ETHERNET_TX_BUFFER_SIZE__   4096

typedef enum{
	ETHERNET_OK=0,
	ETHERNET_NULL_POINTER=1,
	ETHERNET_ZERO_SIZE_PACKET=2,
	ETHERNET_PACKET_TOO_LONG=3	
}ETHERNET_ERRORS;
#endif